### ISSUE TITLE
Remove unneeded dependencies

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#104]
- lightly
- hydra
- omegaconf
- anything else? @surajpaib 

These were the packages installed as dependencies for Lighter after I set up a conda env with pytorch & torchvision:
<img width="1645" alt="image" src="https://github.com/project-lighter/lighter/assets/18015788/5a0f40e6-9c16-4954-bf33-f6e475ae0d23">

**Comment by ibro45** [comment]
Don't confuse lightly with lighter. Also, I don't know how poetry works exactly, but those dependencies are present in https://github.com/project-lighter/lighter/blob/main/poetry.lock.

It seems that hydra and therefore omegaconf are installed by lightly: https://github.com/lightly-ai/lightly/blob/master/tox.ini

**Comment by surajpaib** [comment]
https://github.com/project-lighter/lighter/blob/ca9794e247c886554a88bfcafcf4b910b7037f73/pyproject.toml#L43

Only things here are packaged with poetry. So anything that shows up is either a direct or an indirect dependency of the packages mentioned.

**Comment by surajpaib** [comment]
We should remove lightly in that case as it seems to have somehow remained there
