### ISSUE TITLE
TypeError: Expected type for metric is 'Metric', got 'Tensor' instead.

### ISSUE THREAD

**Issue by surajpaib** [project-lighter/lighter#121]
@ibro45 Your latest pull for subloss logging throws this error while testing `monai_bundle_prototype.yaml`

CI checks pass due to `logger=False` 

Can you debug this for the example?

**Comment by ibro45** [comment]
Ah that's from the dosubot's suggestion, mind removing it for the moment?

**Comment by surajpaib** [comment]
@ibro45 Can you test and fix this? Let's go ahead and release v0.0.3 then
