### ISSUE TITLE
Support more types for data logging in LighterLogger

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#19]
## Description
Currently, only image and single scalar logging is possible. Implement other types as we work on different projects and update the list below:

- [ ] Multiple scalars
- [x] Histograms  https://github.com/project-lighter/lighter/pull/43
- [ ] Strings
- [ ] Audio
- [x] Video  https://github.com/project-lighter/lighter/pull/42
- [ ] ... more to add

The idea is to do these incrementally as we do projects with such data.

References:
- [Tensorboard (all the `add_*` methods)](https://pytorch.org/docs/stable/tensorboard.html)
- [Weights & Biases](https://docs.wandb.ai/ref/python/data-types)

**Comment by surajpaib** [comment]
Current update status:

- [ ] Multiple scalars
- [x] Histograms
- [ ] Strings
- [ ] Audio
- [ ] Video
- [ ] ... more to add

**Comment by surajpaib** [comment]
@ibro45 Another thing that would be nice to support is mask-images. 

https://docs.wandb.ai/ref/python/data-types/imagemask

This probably needs some thinking to fit into our structure of logging right now
