### ISSUE TITLE
Log/upload the config of the run via LighterLogger

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#20]
## Description

Log/upload the config of the run to the loggers. 

It will likely need the config of the run to be dumped before the instantiation of the logger. Probably by `cli.py` into a temp file and then moved into the `log_dir` of the `LighterLogger`. Not a great solution though.

Unfortunately, the config loading and parsing happen in `monai.bundle.run` so we can't access the resolved but non-instantiated config directly.

Think of alternatives.

**Comment by surajpaib** [comment]
Should we open an issue on MONAI for this?

**Comment by ibro45** [comment]
Yes, as we discussed yesterday. Should we go directly with a PR though? Will make it simpler

**Comment by ibro45** [comment]
@surajpaib with the config instantiation that you revamped, we should be able to do it as I suggested in the initial description.

We can dump it into a temp yaml file and have it used by loggers. A bit hacky, would be very happy if you have a better idea, I don't :(
https://github.com/Project-MONAI/MONAI/blob/5657b8f2d297e2d2b09017cf9f57dad2a72186f4/monai/bundle/config_parser.py#L429

If we do come up with a better idea can access the config via `parser[""]`
https://github.com/Project-MONAI/MONAI/blob/5657b8f2d297e2d2b09017cf9f57dad2a72186f4/monai/bundle/config_parser.py#L150
