### ISSUE TITLE
Replace logger.error() and sys.exit() with Exceptions

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#23]

**Comment by surajpaib** [comment]
Continuing the discussion from #15 

I looked at this a bit. 

We can always `raise` some exceptions depending on the nature of the check. For example, we replace this,
```
        if trainer.logger is not None:
            logger.error("When using LighterLogger, set Trainer(logger=None).")
            sys.exit()
```


with `ValueError` as below,

```
        if trainer.logger is not None:
            raise ValueError("When using LighterLogger, set Trainer(logger=None).")

```

We can also define custom errors for the `lighter` library, allowing very fine-grained control in different situations. To move this to the logger, we can use: https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.catch


This should automatically catch all these errors and log them. We can also reraise them so they go to the required exception handlers that an end user might have.

**Comment by kbressem** [comment]
This sounds very good, especially the option to re-raise. For example with `wandb` I would suggest to log an error, but not necessarily re-raise, so the training can still run. Reason behind this is, that maybe I run the training in a HPC environment and forgot to install `wandb`, then I don't want my runs to fail but `lighter` should still notify me, that this is a severe error. It could also be an option to control the behavior if the logger raises with the config, so the user can decide if he/she wants real exceptions or just logging errors?

Custom errors are also a very good idea, like `MissingOptionalImportError` to raise when `wandb` is missing.

**Comment by surajpaib** [comment]
@ibro45 and I discussed this a bit in-person, we can have an environment variable for the logger that determines if we want to re-raise or raise quietly. This will help us raise errors in test environments/jupyter notebook runs and will avoid any breaking in direct usage

**Comment by ibro45** [comment]
Reminder to add `Raises:` to the docstrings

**Comment by surajpaib** [comment]
#44
