### ISSUE TITLE
Track `lighter` package name on pypi

### ISSUE THREAD

**Issue by surajpaib** [project-lighter/lighter#33]
## 🚀 Feature Request
Currently the project goes by `project-lighter` on pypi. 

An issue has been opened on pypi github to request for the name and mail sent to the owner of the name `lighter` 

This issue tracks the progress of this

**Comment by surajpaib** [comment]
@ibro45 Can you link the pypi issues?

**Comment by ibro45** [comment]
https://github.com/pypi/support/issues/2544

Can you comment that you tried reaching out to the owner?

**Comment by surajpaib** [comment]
Closed as this seems like a dead end
