### ISSUE TITLE
Rename `LighterWriter`'s arguments

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#47]
## 🚀 Feature Request

`write_dir` -> `save_dir`,  `write_interval` -> `interval`, `write_format` -> ?. Would be good not to override the built-in `format`. Yes, we are overriding the built-in `input` throughout the code, but the community's used to it because PyTorch does that. Furthermore, almost no one ever uses `input()`, whereas string formatting with `format()` isn't uncommon.

## 🔈 Motivation

`LighterWriter`'s name says it's a writer, no need to repeat that in the arguments.

## 🛰 Alternatives

Override the built-in `format`, or come up with a synonym for format.

**Comment by surajpaib** [comment]
I don't necessarily see the issue with using format. The `format` used for strings is a method for the string class and should be available irrespective of us using the name in the class. 

Given the context, I also think it isn't confusing to use it as it's obvious we are not referring to the method format of string
