### ISSUE TITLE
Issue in unpacking tensor or list of tensors

### ISSUE THREAD

**Issue by surajpaib** [project-lighter/lighter#6]
## Description

While passing `pred` to `self.criterion` in https://github.com/ibro45/lighter/blob/bc91f0aee316e4c72c0f5984df7e2605202bcc40/lighter/system.py#L252, the code breaks if anything other than a tuple, list that can be unpacked is passed. If a scalar tensor is passed, it would break as well. 

## Steps to Reproduce
Run the code with anything other than tuple or list predictions

## Expected outcome
The reason this doesn't work is python tries to unpack the object before evaluating the conditional expression

Attached a sample below and the error,

````
import torch

def test1(a):
    print(a)


def test2(a, b):
    print(a, b)


val_tuple = (2, 3)
val_dict = {
    "a": 2,
    "b": 3
}
val_scalar = torch.Tensor(2)

test2(*val_tuple if isinstance(val_tuple, (list, tuple)) else val_tuple)
test1(*val_scalar if isinstance(val_scalar, (list, tuple)) else val_scalar)
test1(*val_dict if isinstance(val_dict, (list, tuple)) else val_dict)
````

The output of this is,

````

2 3
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    test1(*val_scalar if isinstance(val_scalar, (list, tuple)) else val_scalar)
TypeError: test1() takes 1 positional argument but 2 were given
````

## Potential Solution
Keep the system consistent with only `pred` being passed to the model and the model or a wrapper can handle the input type

**Comment by ibro45** [comment]
The fact that they're one-liners is what causes the issue. Specifically, the asterisk does apply on the variable right after it, but over the whole statement. Essentially, it's not `*val_scalar`, but `*` over the whole thing `val_scalar if isinstance(val_scalar, (list, tuple)) else val_scalar`


This fixes it.
```
import torch

def test1(a):
    print(a)


def test2(a, b):
    print(a, b)


val_tuple = (2, 3)
val_dict = {
    "a": 2,
    "b": 3
}
val_scalar = torch.Tensor(2)

# Tuple
if isinstance(val_tuple, (list, tuple)):
    test2(*val_tuple)
else:
    test2(val_tuple)

# Tensor scalar
if isinstance(val_scalar, (list, tuple)):
    test1(*val_scalar)
else:
    test1(val_scalar)

# Dict
if isinstance(val_dict, (list, tuple)):
    test1(*val_dict)
else:
    test1(val_dict)

```
