### ISSUE TITLE
Auto-publish to PyPI on push to master

### ISSUE THREAD

**Issue by surajpaib** [project-lighter/lighter#63]
## 🚀 Feature Request
Since we make changes to the framework quite often, it would be nice to have a workflow publishing `prereleases` to pypi on any push to master

Pre-releases can only be picked up in `pip` when adding the tag `--pre` 
https://softhints.com/install-pre-release-package-pip-python/

This will prevent stable users from upgrading to a potentially unstable version as well. 

@ibro45 What do you think?

**Comment by ibro45** [comment]
Sounds great!
