### ISSUE TITLE
Replace Hydra with monai bundle

### ISSUE THREAD

**Issue by surajpaib** [project-lighter/lighter#7]
## Issue

Using hydra doesn't let us reference python objects that will get created during config initialization. This introduces a lot of unnecessary code into the framework and the whole `setup` mechanism which can be avoided. 

## Solution

Monai bundle configuration allows us to be a lot more flexible with configuration including referencing other python objects before instantiation of our current object. 
https://docs.monai.io/en/stable/config_syntax.html#to-reference-python-objects-in-configurations

## Additional Information
A huge benefit of this will also be the ability to make our framework monai compatible

**Comment by surajpaib** [comment]
Additionally, instead of setting multiple objects to None, there is also a `_disabled_` flag to skip instantiation

**Comment by ibro45** [comment]
> instead of setting multiple objects to None
What do you mean?
