### ISSUE TITLE
Implement `LoadCheckpoint` callback

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#76]
~`SaveCheckpoint` should be like PL `ModelCheckpoint`, but also allowing saving `k` checkpoints every `n` epochs/steps when monitor isn't used. Also, include the monitor in the checkpoint name so that we know their ranks based on it.~ This can be achieved with multiple `ModelCheckpoint`s.

`LoadCheckpoint` should be able to load the LighterSystem's whole checkpoint state. Probably a good idea to add options to not load certain parts of it - for example, a user might not want to continue with the previous optimizer and instead start from scratch.

**Comment by ibro45** [comment]
@surajpaib, for inspiration
https://docs.monai.io/en/stable/handlers.html#model-checkpoint-loader
https://docs.monai.io/en/stable/handlers.html#model-checkpoint-saver

**Comment by surajpaib** [comment]
@ibro45 Cool! Will look into this today, I need to do some model checkpoint resuming

**Comment by ibro45** [comment]
Ok i think we shouldn't implement `SaveCheckpoint` since we figured we can just use multiple `ModelCheckpoint`s from PL to achieve what we described above. However a `LoadCheckpoint` would be useful. It should include the 
 features from `adjust_prefix_and_load_state_dict`, and `adjust_prefix_and_load_state_dict` should be removed
