### ISSUE TITLE
RAM Memory leak when predicting

### ISSUE THREAD

**Issue by ibro45** [project-lighter/lighter#82]
## 🐛 Bug Report

There is a RAM (not VRAM) memory leak when predicting. Could not identify where it's coming from. Seems that it's neither Writer nor `postprocessing` (even though postprocessing can increase it). Need to check if it's related to Monai in any way (e.g. MetaTensor) as I've only been predicting on them recently.

**Comment by ibro45** [comment]
@surajpaib you mentioned a somewhat similar issue which may be due to PL, could you please describe it here for reference? May not be related to this but anyway.

**Comment by surajpaib** [comment]
While the issue I mentioned earlier wasn't related to this, I do have the same issue you mentioned right now. I realized this while trying to run 4 separate prediction scripts across 4 GPUs and all of them except one kept getting killed. 

On investigating more, it definitely seems like there is a memory leak as RAM usage keeps increasing throughout the prediction loop and gets to quite unrealistic numbers toward the end. 

We should definitely investigate this more. 

@dosubot Can you find more instances of this in other repositories?

**Comment by surajpaib** [comment]
Opened issue on PL Github with more info: https://github.com/Lightning-AI/pytorch-lightning/issues/19398

**Comment by ibro45** [comment]
Closing it as fixed in https://github.com/project-lighter/lighter/pull/106.
If PL fixes the issue, we'll update it.
