### ISSUE TITLE
`TableWriter` replace directory with path to CSV

### ISSUE THREAD

**Issue by surajpaib** [project-lighter/lighter#90]
https://github.com/project-lighter/lighter/blob/5741df30c4cd1b86c76216247cb67f3748ecf1d6/lighter/callbacks/writer/table.py#L25C28-L25C28

**Comment by surajpaib** [comment]
@ibro45 I don't see any benefit gained by keeping this a directory

**Comment by ibro45** [comment]
You're right. I guess we can just get the parent dir of the csv file and pass it to the super init(), wdy think?

**Comment by surajpaib** [comment]
@dosubot
